server:
  port: 9090

spring:
  flyway:
    enabled: true
  datasource:

    # MySQL Configuration Example
    # url: jdbc:mysql://localhost:3306/easy_recon_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    # driverClassName: com.mysql.cj.jdbc.Driver
    # username: root
    # password: your_password

    # H2 Configuration for Demo
    # url: jdbc:h2:mem:easy_recon;DB_CLOSE_DELAY=-1;MODE=MySQL
    # driverClassName: org.h2.Driver
    # username: sa
    # password: 

    # PostgreSQL Configuration Example (Disabled for now)
     url: jdbc:postgresql://localhost:5432/easy_recon_demo
     driverClassName: org.postgresql.Driver
     username: postgresql
     password: postgresql
    
  # jpa:
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect
  #   hibernate:
  #     ddl-auto: update

easy-recon:
  enabled: true
  timing:
    enabled: true
  timing-cron: "0 0 2 * * ?" # 每天凌晨2点执行
  alarm:
    type: log

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
