spring:
  flyway:
    enabled: true
  datasource:

    # MySQL Configuration Example
    # url: jdbc:mysql://localhost:3306/easy_recon_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    # driverClassName: com.mysql.cj.jdbc.Driver
    # username: root
    # password: your_password

    # PostgreSQL Configuration Example
    url: jdbc:postgresql://localhost:5432/easy_recon_demo
    driverClassName: org.postgresql.Driver
    username: postgresql
    password: postgresql
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

easy-recon:
  enabled: true
  timing:
    enabled: true
  timing-cron: "0 0 2 * * ?" # 每天凌晨2点执行
  alarm:
    type: log

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
