name: Java Package

on:
  push:
    tags:
      - 'java/v*'
    paths:
      - 'sdk/spring-boot-starter/**'
      - '.github/workflows/java-publish.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


      - name: Configure Maven for GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}/.github

      - name: Build with Maven
        run: mvn -B package --file sdk/spring-boot-starter/pom.xml

      - name: Publish to Maven Central
        run: mvn -B deploy --file sdk/spring-boot-starter/pom.xml -P release
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Publish to GitHub Packages
        run: |
          mvn -B deploy --file sdk/spring-boot-starter/pom.xml \
          -s ${{ github.workspace }}/.github/settings.xml \
          -DskipTests -Dmaven.install.skip=true \
          -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/coffersTech/easy-recon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}