name: Python Package

on:
  push:
    tags:
      - 'sdk/python/v*'
    paths:
      - 'sdk/python/**'
      - '.github/workflows/python-publish.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version
      id: extract_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/sdk/python/v}
        else
          VERSION="0.0.0.dev"
        fi
        echo "SDK_VERSION=$VERSION" >> $GITHUB_ENV
        echo "Released version: $VERSION"
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      working-directory: ./sdk/python
      run: python -m build

    - name: Publish to PyPI
      working-directory: ./sdk/python
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PY_PACKAGE_TOKEN }}
      run: |
        python -m twine upload dist/*